In [199]:
import numpy as np

# 1D array

oneDarray = np.array([1,2,3,4])
print(oneDarray)

[1 2 3 4]


In [200]:
# 2d array
twoDarray = np.array([[1,2,3],[4,5,6]])
print(twoDarray)

[[1 2 3]
 [4 5 6]]


In [201]:
# 3D array
threeDarray = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,6,3]]])
print(threeDarray)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 6 3]]]


In [202]:
# array indexing

print(oneDarray[2])
print(twoDarray[0,1])
print(threeDarray[1,0,1])

# array slicing

print()
print(twoDarray)
print()
print(twoDarray[0:,1])
print(twoDarray[1,0:2])
print(twoDarray[:2,1:])

3
2
8

[[1 2 3]
 [4 5 6]]

[2 5]
[4 5]
[[2 3]
 [5 6]]


In [203]:
# iterating over numpy array

for i in oneDarray:
    print(i)

1
2
3
4


In [204]:
# for 2D array
for i in twoDarray:
    for j in i:
        print(j)

1
2
3
4
5
6


In [205]:
# for 2D array
for i in threeDarray:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
9
6
3


In [206]:
# Array Attributes
print('ndim:- ' + str( twoDarray.ndim)) # dimention of the array
print('shape:- ' + str(twoDarray.shape)) # rows and columns
print('size:- ' + str(twoDarray.size)) # total element in array
print('dtype:- ' + str(twoDarray.dtype)) # data type of array's element
print('itemsize:- ' + str(twoDarray.itemsize)) # size in bites of each element in array
print('len:- ' + str(len(twoDarray))) # length of the array

ndim:- 2
shape:- (2, 3)
size:- 6
dtype:- int64
itemsize:- 8
len:- 2


In [207]:
# conversion of data type
print(twoDarray)
print(twoDarray.astype(float))
print(twoDarray.astype(str))

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
[['1' '2' '3']
 ['4' '5' '6']]


In [208]:
#Creating arrays with predefined values: np.zeros(), np.ones(), np.full(), np.eye(), np.empty().
  # Creating arrays with ranges: np.arange(), np.linspace().
print('#Creating arrays with predefined values:')
print(' np.zeros(), np.ones(), np.full(), np.eye(), np.empty(),np.arange(), np.linspace().')
print('# Creating arrays with ranges: np.arange(), np.linspace().')
print()
print()

#Creating arrays with predefined values:
 np.zeros(), np.ones(), np.full(), np.eye(), np.empty(),np.arange(), np.linspace().
# Creating arrays with ranges: np.arange(), np.linspace().




In [209]:
# array creation function
import numpy as np

# zeros(row,col)
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [210]:
# ones(row,col)
ones = np.ones((5,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [211]:
# full((row,col),fill_value)
full = np.full((3,3),7)
print(full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [212]:
# eye(n) create an identity matrix
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [213]:
# arange(start,stop,step)
arange = np.arange(0,10,2)
print(arange)

[0 2 4 6 8]


In [214]:
# linspace(start,stop,num)
linspace = np.linspace(0,2,5)
print(linspace)

[0.  0.5 1.  1.5 2. ]


In [215]:
# random(row,col)
random = np.random.random((2,3))
print(random)

[[0.38101506 0.8280656  0.83112824]
 [0.31092278 0.52313607 0.75285964]]


In [216]:
print('# Array operation')
print('   # mathmetical operation')
print()
print()

# Array operation
   # mathmetical operation




In [217]:
# array operation
    # array operation
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,2,1],[6,5,4]])

print(a + b)

[[ 4  4  4]
 [10 10 10]]


In [218]:
print(a-b)

[[-2  0  2]
 [-2  0  2]]


In [219]:
print(a*b)

[[ 3  4  3]
 [24 25 24]]


In [220]:
print(a/b)

[[0.33333333 1.         3.        ]
 [0.66666667 1.         1.5       ]]


In [221]:
# mathmetical operation
exponential = np.exp(a)
print(exponential)

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [222]:
arr1 = np.array([2])
power = np.power(a,arr1)
print(power)

[[ 1  4  9]
 [16 25 36]]


In [223]:
arr2 = np.array([[1,4,9],[16,25,36]])
sqrt = np.sqrt(arr2)
print(sqrt)

[[1. 2. 3.]
 [4. 5. 6.]]


In [224]:
#Broadcasting
arr3 = np.array([1,2,3])
arr4 = np.array([[3],[2],[1]])
print(arr3 + arr4)

[[4 5 6]
 [3 4 5]
 [2 3 4]]


In [225]:
# adding and removing*: append(), insert(), delete().

print('# adding and removing*: append(), insert(), delete()')
print()
print()
print()

# adding and removing*: append(), insert(), delete()





In [226]:
# adding and removing*: append(), insert(), delete().
oneDarray = np.array([1,2,3,4])
twoDarray = np.array([[1,2,3],[3,2,1]])
print('append:-')
print(np.append(oneDarray,9))
print(np.append(twoDarray,[90,30]))

append:-
[1 2 3 4 9]
[ 1  2  3  3  2  1 90 30]


In [227]:
oneDarray = np.array([1,2,3,4])
twoDarray = np.array([[1,2,3],[3,2,1]])

print('insert:-')
print(np.insert(oneDarray,1,50))
print(np.insert(twoDarray,1,[50,60]))
print()
print(np.insert(twoDarray,1,[50,60], axis=1)) # axis = 1 means column or y-axis 
print()
print(np.insert(twoDarray,1,[50,60,70], axis=0)) # axis = 0 means row or x-axis 

insert:-
[ 1 50  2  3  4]
[ 1 50 60  2  3  3  2  1]

[[ 1 50  2  3]
 [ 3 60  2  1]]

[[ 1  2  3]
 [50 60 70]
 [ 3  2  1]]


In [228]:
oneDarray = np.array([1,2,3,4])
twoDarray = np.array([[1,2,3],[3,2,1]])

print('delete:-')
print(twoDarray)
print()
print(np.delete(twoDarray,1))
print()
print(np.delete(twoDarray,1,axis=0))
print()
print(np.delete(twoDarray,1,axis=1))

delete:-
[[1 2 3]
 [3 2 1]]

[1 3 3 2 1]

[[1 2 3]]

[[1 3]
 [3 1]]


In [229]:
# numpy sort(), filter(), search()

print('# numpy sort(), filter(), search()')
print()
print()
print()

# numpy sort(), filter(), search()





In [230]:
# numpy sort(), filter(), search()
oneDarray = np.array([7,3,4,2,8,1])
twoDarray = np.array([[3,2,1],[6,5,4]])
print(np.sort(oneDarray))
print(np.sort(twoDarray))

[1 2 3 4 7 8]
[[1 2 3]
 [4 5 6]]


In [231]:
   # search by where()
s = np.where(oneDarray == 4)
print(s)
   # or by condition
s = np.where(oneDarray % 2 == 0)
print(s)
   # search by sorted data by searchsorted(array,value)
sorted = np.sort(oneDarray)
print(np.searchsorted(sorted,7))

(array([2]),)
(array([2, 3, 4]),)
4


In [232]:
#   filter by boolean and by condition
arr = np.array([10,20,30,40])
filtervalue = [False,False,True,False]
new = arr[filtervalue]
print(new)

fv = arr>25
print(arr[fv])

[30]
[30 40]


In [251]:
# Shape Manipulation
    #Concatenation and Splitting*: np.concatenate(), np.vstack(), np.hstack(), np.split(), np.hsplit(), np.vsplit().

print('#Concatenation and Splitting*: np.concatenate(), np.vstack(), np.hstack(), np.split(), np.hsplit(), np.vsplit().')
print()
print()
print()

#Concatenation and Splitting*: np.concatenate(), np.vstack(), np.hstack(), np.split(), np.hsplit(), np.vsplit().





In [234]:
#Concatenation
oneDarray = np.array([7,3,4,2,8,1])
twoDarray = np.array([[3,2,1],[6,5,4]])
oneDarray1 = np.array([1,2,3,4])
twoDarray1 = np.array([[1,2,3],[3,2,1]])

print(np.concatenate([oneDarray,oneDarray1]))
print(np.concatenate([twoDarray,twoDarray1]))# by default axis 0 or x-axis
print()
print(np.concatenate([twoDarray,twoDarray1],axis=1)) # axis = 1

[7 3 4 2 8 1 1 2 3 4]
[[3 2 1]
 [6 5 4]
 [1 2 3]
 [3 2 1]]

[[3 2 1 1 2 3]
 [6 5 4 3 2 1]]


In [235]:
# np.hstack()
print(np.hstack([twoDarray,twoDarray1])) # Horizontal concatenation

[[3 2 1 1 2 3]
 [6 5 4 3 2 1]]


In [236]:
# np.vstack()
print(np.vstack([twoDarray,twoDarray1])) # Vertical concatenation

[[3 2 1]
 [6 5 4]
 [1 2 3]
 [3 2 1]]


In [237]:
# np.split()
print(oneDarray)
print(twoDarray)
print()
print(np.split(oneDarray,3))
print(np.split(oneDarray,2))
print()
print(np.split(twoDarray,2))

[7 3 4 2 8 1]
[[3 2 1]
 [6 5 4]]

[array([7, 3]), array([4, 2]), array([8, 1])]
[array([7, 3, 4]), array([2, 8, 1])]

[array([[3, 2, 1]]), array([[6, 5, 4]])]


In [238]:
# np.hsplit()
twoDarray1 = np.array([[1,2,3],[3,2,1],[3,2,4]])
print(oneDarray)
print(twoDarray)
print(twoDarray1)
print()
print(np.hsplit(twoDarray,3))
#horizontal = np.hsplit(twoDarray,2)
print(np.hsplit(twoDarray1,3))

[7 3 4 2 8 1]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [3 2 1]
 [3 2 4]]

[array([[3],
       [6]]), array([[2],
       [5]]), array([[1],
       [4]])]
[array([[1],
       [3],
       [3]]), array([[2],
       [2],
       [2]]), array([[3],
       [1],
       [4]])]


In [239]:
# np.vsplit()
print(np.vsplit(twoDarray,2))
print(np.vsplit(twoDarray1,3))

[array([[3, 2, 1]]), array([[6, 5, 4]])]
[array([[1, 2, 3]]), array([[3, 2, 1]]), array([[3, 2, 4]])]


In [240]:
# Reshaping Arrays*: Using reshape(), ravel(), flatten(), transpose().
# reshape(): Changes the shape of the array without changing its data.
# ravel(): Flattens the array.
# transpose(): Transposes the array.
print('Reshaping Arrays*: Using reshape(), ravel(), flatten(), transpose()')
print()
print()
print()

Reshaping Arrays*: Using reshape(), ravel(), flatten(), transpose()





In [241]:
# reshape(): 
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print()
print(array.reshape((3,2)))

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [242]:
# ravel(): Flattens the array.
print(array.ravel())
print(array.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [243]:
# transpose(): Transposes the array.
print(array.transpose())
transposed = array.transpose()
print()
print(transposed.transpose())

[[1 4]
 [2 5]
 [3 6]]

[[1 2 3]
 [4 5 6]]


In [244]:
# Aggregation Functions*: np.sum(), np.mean(), np.max(), np.min(), np.std(), np.var().
# np.sum(): Sum of all elements.
# np.min(): Minimum element.
# np.max(): Maximum element.
# np.mean(): Mean of all elements.
# np.std(): Standard deviation of all elements.
# np.var(): Variance of all elements.

print('Aggregation Functions*: np.sum(), np.mean(), np.max(), np.min(), np.std(), np.var().')
print()
print()
print()

Aggregation Functions*: np.sum(), np.mean(), np.max(), np.min(), np.std(), np.var().





In [245]:
# Aggregation Functions*: np.sum(), np.mean(), np.max(), np.min(), np.std(), np.var().
print(oneDarray)
print(np.sum(oneDarray))
print(np.mean(oneDarray))
print(np.max(oneDarray))
print(np.min(oneDarray))
print(np.std(oneDarray))
print(np.var(oneDarray))
print('with 2d array  ⤵⤵⤵⬇⬇⬇')

[7 3 4 2 8 1]
25
4.166666666666667
8
1
2.544056253745625
6.472222222222222
with 2d array  ⤵⤵⤵⬇⬇⬇


In [246]:
# with 2d array
print(twoDarray)
print(np.sum(twoDarray))
print(np.mean(twoDarray))
print(np.max(twoDarray))
print(np.min(twoDarray))
print(np.std(twoDarray))
print(np.var(twoDarray))

[[3 2 1]
 [6 5 4]]
21
3.5
6
1
1.707825127659933
2.9166666666666665


In [247]:
# Trigonometric functions: np.sin(), np.cos(), np.tan()

print('# Trigonometric functions: np.sin(), np.cos(), np.tan()')
print()
print()
print()

# Trigonometric functions: np.sin(), np.cos(), np.tan()





In [248]:
# Trigonometric functions: np.sin(), np.cos(), np.tan()

print(oneDarray)
print(np.sin(oneDarray))
print(np.cos(oneDarray))
print(np.tan(oneDarray))

[7 3 4 2 8 1]
[ 0.6569866   0.14112001 -0.7568025   0.90929743  0.98935825  0.84147098]
[ 0.75390225 -0.9899925  -0.65364362 -0.41614684 -0.14550003  0.54030231]
[ 0.87144798 -0.14254654  1.15782128 -2.18503986 -6.79971146  1.55740772]


In [249]:
# Linear Algebra*: np.dot(), np.linalg.inv(), np.linalg.det(), np.linalg.eig()
# NumPy provides various functions for linear algebra:
# np.dot(): Dot product of two arrays.
# np.linalg.inv(): Inverse of a matrix.
# np.linalg.det(): Determinant of a matrix.
# np.linalg.eig(): Eigenvalues and eigenvectors of a matrix.
print('Linear Algebra*: np.dot(), np.linalg.inv(), np.linalg.det(), np.linalg.eig()')
print()
print()
print()

Linear Algebra*: np.dot(), np.linalg.inv(), np.linalg.det(), np.linalg.eig()





In [250]:
# Linear Algebra*: np.dot(), np.linalg.inv(), np.linalg.det(), np.linalg.eig()
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([5, 6])

print(matrix, '/n',vector)
print()
print(np.dot(matrix, vector))
print(np.linalg.inv(matrix))
print(np.linalg.det(matrix))
print(np.linalg.eig(matrix))

[[1 2]
 [3 4]] /n [5 6]

[17 39]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
